export type AuditEvent = {
  id: number;
  event_fingerprint: string;
  timestamp: string;
  result: string;
  actor: string;
  action: string;
  normalized_action: string;
  action_category: string;
  resource_type: string;
  resource_name: string;
  resource_display: string;
  resource_display_name: string;
  cluster_id?: string | null;
  cluster_name?: string | null;
  source_ip?: string | null;
  summary: string;
  is_failure: boolean;
  is_denied: boolean;
  is_routine_noise: boolean;
  impact_type: string;
  risk_level: string;
  change_type: string;
  resource_family: string;
  event_title: string;
  event_summary: string;
  subject: string;
  subject_type: string;
  actor_display_name: string;
  actor_email?: string | null;
  actor_type: string;
  actor_raw_id?: string | null;
  actor_source?: string;
  actor_confidence?: string;
  actor_enriched_at?: string | null;
  resource_display_short: string;
  source_context: string;
  environment_name?: string | null;
  parent_resource?: string | null;
  resource_scope: string;
  resource_criticality: string;
  blast_radius_hint: string;
  production_hint: string;
  source_display?: string;
  source_reason?: string;
  client_id?: string | null;
  connection_id?: string | null;
  request_id?: string | null;
  environment_id?: string | null;
  flink_region?: string | null;
  network_id?: string | null;
  signal_type: string;
  signal_reason: string;
  decision_reason: string;
  decision_label: string;
  recommended_action: string;
  triage_status: string;
  triage_actor?: string | null;
  triage_timestamp?: string | null;
  triage_note?: string | null;
  raw_payload_json?: string;
};

export type EventListResponse = {
  items: AuditEvent[];
  limit: number;
  offset: number;
  total: number;
  scanned_events: number;
  signal_filter_applied: boolean;
  hide_noise_applied: boolean;
  result_limit_reached: boolean;
  debug?: Record<string, unknown> | null;
};

export type SummaryResponse = {
  total_events: number;
  scanned_events: number;
  failures: number;
  denials: number;
  noise_count: number;
  informational_count: number;
  attention_count: number;
  action_required_count: number;
  failure_count: number;
  denied_count: number;
  destructive_count: number;
  configuration_change_count: number;
  access_change_count: number;
  top_subjects: Array<{ value: string; count: number }>;
  top_resources: Array<{ value: string; count: number }>;
  top_actions: Array<{ value: string; count: number }>;
  top_signal_reasons: Array<{ value: string; count: number }>;
  flow_groups: Array<{
    group_title: string;
    group_summary: string;
    event_count: number;
    first_seen: string;
    last_seen: string;
    subject: string;
    signal_type: string;
    decision_label: string;
    risk_level: string;
    impact_type: string;
    resource_family: string;
    resource_display_short: string;
    recommended_action: string;
    representative_event_ids?: number[];
  }>;
  overall_status: string;
  summary_scope: string;
  sample_limit: number;
  sample_warning?: string | null;
  headline: string;
  short_digest: string;
  by_action_category: Record<string, number>;
  by_resource_type: Record<string, number>;
  by_result: Record<string, number>;
};

export type FilterOptions = {
  resource_types: string[];
  action_categories: string[];
  results: string[];
  actors: string[];
};

export type SystemStatus = {
  consumer_state: string;
  last_successful_poll?: string | null;
  retry_count: number;
  consecutive_error_count: number;
  last_error?: string | null;
  consumer_lag?: number | null;
  records_consumed_total: number;
  db_writer_enabled: boolean;
  db_writer_state: string;
  db_write_success_total: number;
  db_write_error_total: number;
  db_write_batch_size: number;
  db_last_successful_write?: string | null;
  db_last_error?: string | null;
  db_last_cleanup_at?: string | null;
  db_last_cleanup_deleted_count: number;
  storage_usage: Record<string, unknown>;
  database_mode: string;
  db_health?: Record<string, unknown>;
};
